######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 31 14:43:17 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
