######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 31 16:12:53 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
