######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 1 20:41:10 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += testy.h
FORMS += testyWindow.ui
SOURCES += main.cpp testy.cpp
