######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 31 15:14:39 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += age.cpp
